
INPUT_IMAGE = "busybox:latest"
DOCKERFILE_GIT = "https://github.com/TomasTomecek/docker-hello-world.git"

REGISTRY_PORT = "5000"
DOCKER0_IP = "172.17.42.1"

LOCALHOST_REGISTRY = "localhost:%s" % REGISTRY_PORT
DOCKER0_REGISTRY = "%s:%s" % (DOCKER0_IP, REGISTRY_PORT)
LOCALHOST_REGISTRY_HTTP = "http://%s" % LOCALHOST_REGISTRY
DOCKER0_REGISTRY_HTTP = "http://%s" % DOCKER0_REGISTRY
