apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: binary-container-0-2  # dot is not allowed in the name
spec:
  params:
    - name: osbs-image
      description: The location of the OSBS builder image (FQDN pullspec)
      type: string
    - name: hermeto-image
      description: The location of the Hermeto image (FQDN pullspec)
      type: string
    - name: user-params
      type: string
      description: User parameters in JSON format

  workspaces:
    - name: ws-container
    - name: ws-home-dir
    - name: ws-registries-secret
    - name: ws-koji-secret
    - name: ws-reactor-config-map
    - name: ws-remote-host-auth
    - name: ws-autobot-keytab
    - name: netrc
      description: |
        Workspace containing a .netrc file. OSBS and Hermeto will use the credentials in this file when
        performing git/http(s) requests.
      optional: true
    - name: git-ssh-privkey
      description: |
        Workspace containing an id_rsa file. OSBS and Hermeto will use the credentials in this file when
        performing ssh git requests.
      optional: true

  results:
    - name: repositories
      value: $(tasks.binary-container-set-results.results.repositories)
    - name: koji-build-id
      value: $(tasks.binary-container-set-results.results.koji-build-id)
    - name: task_build_result_x86_64
      value: $(tasks.binary-container-build-x86-64.results.task_result)
    - name: task_build_result_s390x
      value: $(tasks.binary-container-build-s390x.results.task_result)
    - name: task_build_result_ppc64le
      value: $(tasks.binary-container-build-ppc64le.results.task_result)
    - name: task_build_result_aarch64
      value: $(tasks.binary-container-build-aarch64.results.task_result)
    - name: platforms_result
      value: $(tasks.binary-container-init.results.platforms_result)
    - name: annotations
      value: $(finally.binary-container-exit.results.annotations)

  tasks:
    - name: clone
      taskRef:
        name: clone-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
      timeout: "0"

    - name: binary-container-init
      runAfter:
        - clone
      taskRef:
        name: binary-container-init-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-autobot-keytab
          workspace: ws-autobot-keytab
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
      timeout: "0"

    - name: binary-container-cachito
      runAfter:
        - binary-container-init
      taskRef:
        name: binary-container-cachito-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-autobot-keytab
          workspace: ws-autobot-keytab
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
      when:
        - input: "$(tasks.binary-container-init.results.remote_sources_version_result)"
          operator: in
          values: ["1"]
      timeout: "0"

    - name: binary-container-hermeto
      runAfter:
        - binary-container-init
      taskRef:
        name: binary-container-hermeto-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-autobot-keytab
          workspace: ws-autobot-keytab
        - name: netrc
          workspace: netrc
        - name: git-ssh-privkey
          workspace: git-ssh-privkey
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: hermeto-image
          value: "$(params.hermeto-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
      when:
        - input: "$(tasks.binary-container-init.results.remote_sources_version_result)"
          operator: in
          values: ["2"]
      timeout: "0"

    - name: binary-container-prebuild
      runAfter:
        - binary-container-cachito
        - binary-container-hermeto
      taskRef:
        name: binary-container-prebuild-0-2
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-autobot-keytab
          workspace: ws-autobot-keytab
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
      timeout: "0"

    - name: binary-container-build-x86-64
      runAfter:
        - binary-container-prebuild
      taskRef:
        name: binary-container-build-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-remote-host-auth
          workspace: ws-remote-host-auth
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
        - name: platform
          value: x86_64
      timeout: "0"

    - name: binary-container-build-s390x
      runAfter:
        - binary-container-prebuild
      taskRef:
        name: binary-container-build-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-remote-host-auth
          workspace: ws-remote-host-auth
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
        - name: platform
          value: s390x
      timeout: "0"

    - name: binary-container-build-ppc64le
      runAfter:
        - binary-container-prebuild
      taskRef:
        name: binary-container-build-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-remote-host-auth
          workspace: ws-remote-host-auth
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
        - name: platform
          value: ppc64le
      timeout: "0"

    - name: binary-container-build-aarch64
      runAfter:
        - binary-container-prebuild
      taskRef:
        name: binary-container-build-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-remote-host-auth
          workspace: ws-remote-host-auth
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
        - name: platform
          value: aarch64
      timeout: "0"

    - name: binary-container-postbuild
      runAfter:
        - binary-container-build-x86-64
        - binary-container-build-s390x
        - binary-container-build-ppc64le
        - binary-container-build-aarch64
      taskRef:
        name: binary-container-postbuild-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
        - name: ws-remote-host-auth
          workspace: ws-remote-host-auth
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
      timeout: "0"

    - name: binary-container-set-results
      runAfter:
        - binary-container-postbuild
      taskRef:
        name: binary-container-set-results-0-1
      workspaces:
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
      timeout: "0"

  finally:
    - name: binary-container-exit
      taskRef:
        name: binary-container-exit-0-1
      workspaces:
        - name: ws-build-dir
          workspace: ws-container
          subPath: build-dir
        - name: ws-context-dir
          workspace: ws-container
          subPath: context-dir
        - name: ws-home-dir
          workspace: ws-home-dir
        - name: ws-registries-secret
          workspace: ws-registries-secret
        - name: ws-koji-secret
          workspace: ws-koji-secret
        - name: ws-reactor-config-map
          workspace: ws-reactor-config-map
      params:
        - name: osbs-image
          value: "$(params.osbs-image)"
        - name: pipeline-run-name
          value: "$(context.pipelineRun.name)"
        - name: user-params
          value: '$(params.user-params)'
      timeout: "0"
